version: '3.8'
volumes:
  sqlserver_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssword1
      - MSSQL_PID=Developer
    ports:
    - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P StrongP@ssword1 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s